### ISSUE TITLE
TypeError: value.toArrayBuffer is not a function

### ISSUE THREAD

**Issue by timkuijsten** [maxogden/level.js#50]
I'm running into the exception that toArrayBuffer is not a method of `value` on line [#68](https://github.com/maxogden/level.js/blob/master/index.js#L68). I wonder if this code in #L67-L68 is correct and what the purpose of it is? I really have no clue, for now I just disabled #L67-L69 and "It works for me".

**Comment by nolanlawson** [comment]
Hm, the point of that line is that IndexedDB supposedly accepts Uint8Array objects, but not "Buffer" objects (which are a shim for the Node.js "Buffer" object). If you can provide a test case to reproduce and let us know which browser it failed in, that would be helpful. :)

**Comment by timkuijsten** [comment]
I've written a new approach where native types are supported if asBuffer is false. I'm interested in feedback on it, see #46.
